const bookmarks = [
  {
    title: "Bruh",
    links: [
      { name: "Tele", url: "https://alplox.github.io/tele/" },
      { name: "Covid-19", url: "https://datastudio.google.com/reporting/b1689869-0c59-442c-951d-2991c0fc611d/page/rUZIB" },
      { name: "Google News", url: "https://news.google.com" },
      { name: "Microsoft News", url: "https://microsoftnews.msn.com/" },
      { name: "Google Trends", url: "https://trends.google.com/trends/trendingsearches/daily?geo=CL" },
      { name: "Inbox", url: "https://inbox.google.com" },
      { name: "Google Keep", url: "https://keep.google.com/u/0/" },
      { name: "Google Drive", url: "https://drive.google.com/drive/" },
      { name: "Pi-Hole", url: "http://192.168.0.2" },
      { name: "Plex", url: "http://127.0.0.1:32400/web/index.html" },
      { name: "Steamgifts", url: "https://www.steamgifts.com/" },
      { name: "Github", url: "https://github.com" },
      { name: "Gitlab", url: "https://gitlab.com" },
      { name: "WhatsApp", url: "https://web.whatsapp.com/" },
      { name: "Twitter", url: "https://www.twitter.com/" },
      { name: "Instagram", url: "https://www.instagram.com/" },
      { name: "Telegram", url: "https://web.telegram.org/" },
    ],
  },
  {
    title: "(old)Reddit",
    links: [
      { name: "/r/FreeGameFindings", url: "https://old.reddit.com/r/FreeGameFindings/" },
      { name: "/r/chile", url: "https://old.reddit.com/r/chile/" },
      { name: "/r/movies", url: "https://old.reddit.com/r/movies/" },
      { name: "/r/hacking", url: "https://old.reddit.com/r/hacking/" },
      { name: "/r/Piracy", url: "https://old.reddit.com/r/Piracy/" },
      { name: "/r/privacy", url: "https://old.reddit.com/r/privacy/" },
      { name: "/r/DataHoarder", url: "https://old.reddit.com/r/DataHoarder/" },
      { name: "/r/homelab", url: "https://old.reddit.com/r/homelab/" },   
      // WEB DEV
      { name: "/r/webdev", url: "https://old.reddit.com/r/webdev/" },
      { name: "/r/web_design", url: "https://old.reddit.com/r/web_design/" },
      { name: "/r/Frontend", url: "https://old.reddit.com/r/Frontend/" },
      { name: "/r/javascript", url: "https://old.reddit.com/r/javascript/" },
      // INSPO
      { name: "/r/Art", url: "https://old.reddit.com/r/Art/" },
      { name: "/r/battlestations", url: "https://old.reddit.com/r/battlestations" },
      { name: "/r/unixporn", url: "https://old.reddit.com/r/unixporn" },
      { name: "/r/startpages", url: "https://old.reddit.com/r/startpages/" },
      // ?
      { name: "/r/worldnews", url: "https://old.reddit.com/r/worldnews/" },
      { name: "/r/science", url: "https://old.reddit.com/r/science/" },
      { name: "/r/IIB", url: "https://old.reddit.com/r/InternetIsBeautiful/" },
      { name: "/r/WSB", url: "https://old.reddit.com/r/wallstreetbets/" },
      { name: "/r/composting", url: "https://old.reddit.com/r/composting/" },
      
    ],
  },
  {
    title: "Boards",
    links: [
      { name: "/tv/", url: "https://boards.4channel.org/tv/" },
      { name: "/g/", url: "https://boards.4channel.org/g/" },
      { name: "/mu/", url: "https://boards.4channel.org/mu/" },
      { name: "/gd/", url: "https://boards.4channel.org/gd/" },
      { name: "/fa/", url: "https://boards.4channel.org/fa/" },
      { name: "/fit/", url: "https://boards.4channel.org/fit/" },
      { name: "/biz/", url: "https://boards.4channel.org/biz/" },
      { name: "/r9k/", url: "https://boards.4chan.org/r9k/" },
      { name: "/v/", url: "https://boards.4channel.org/v/" },
      { name: "/wsg/", url: "https://boards.4channel.org/wsg/" },
      { name: "/λ/", url: "https://www.lainchan.org/%CE%BB/catalog.html" },
      { name: "/sec/", url: "https://www.lainchan.org/sec/catalog.html" },
      { name: "/music/", url: "https://lainchan.org/music/catalog.html" },
      { name: "/vis/", url: "https://lainchan.org/vis/index.html" },
      { name: "/Ω/", url: "https://lainchan.org/%CE%A9/catalog.html" },
    ],
  },
  {
    title: "🎥/🎵/📻",
    links: [
      { name: "🎥Youtube", url: "https://youtube.com" },
      { name: "🎥Twitch", url: "https://www.twitch.tv" },
      { name: "🎥Udemy", url: "https://www.udemy.com/" },
      { name: "🎥Ondamedia", url: "https://ondamedia.cl/" },
      { name: "🎵Spotify", url: "https://open.spotify.com" },
      { name: "🎵Soundcloud", url: "https://soundcloud.com" },
      { name: "🎵Deathgrind", url: "https://deathgrind.club/" },
      { name: "📻Coreradio", url: "https://coreradio.ru/" },
      { name: "📻Radio.garden", url: "https://radio.garden/" },
      { name: "📻Plaza.one", url: "https://plaza.one/" },
      { name: "📻Radiooooo", url: "https://radiooooo.com/" },
      { name: "📻Rainwave", url: "https://rainwave.cc/all/" },
      { name: "📻Poolside", url: "https://poolside.fm/" },
      { name: "📻Cmd.to", url: "https://cmd.to/fm" },
      { name: "📻R-a-d.io", url: "https://r-a-d.io/" },
      { name: "📻Listen.moe", url: "https://listen.moe/" },
      { name: "📻Di.fm", url: "https://www.di.fm/" },
      //Background noise generators
      { name: "📻Asoftmurmur", url: "https://asoftmurmur.com/" },
      { name: "📻Naturemixer", url: "https://naturemixer.com" },
      { name: "📻Moodil", url: "https://www.moodil.com/" },
      { name: "📻Rainymood", url: "https://www.rainymood.com/" },
      { name: "📻Soundscape", url: "https://soundscape.world/" },
    ],
  },
  {
    title: "Tools/Inspo",
    links: [
      //Tools
      { name: "Temp-mail", url: "https://temp-mail.org" },
      { name: "Virustotal", url: "https://www.virustotal.com/" },
      { name: "Recursos", url: "https://github.com/Alplox/mi-bitacora-webdev/blob/main/lista-recursos.md" },
      { name: "G Translate", url: "https://translate.google.com/" },
      { name: "D Translate", url: "https://www.deepl.com/en/translator" },
      { name: "Photopea", url: "https://www.photopea.com/" },
      { name: "Pixlr E", url: "https://pixlr.com/es/e/" },
      { name: "Paint sumo.app", url: "https://sumo.app/paint/en" },
      { name: "Waifu2x", url: "http://waifu2x.udp.jp/" },
      { name: "Waifu2x.pro", url: "https://waifu2x.pro/" },
      { name: "Waifu2x.booru", url: "https://waifu2x.booru.pics/" },
      { name: "Speedtest.net", url: "https://www.speedtest.net/" },
      { name: "Speed.cloudflare", url: "https://speed.cloudflare.com/" },
      { name: "Dnsleaktest", url: "https://www.dnsleaktest.com/" },
      { name: "Ciberpatrulla", url: "https://ciberpatrulla.com/links/" },
      { name: "Osintframework", url: "https://osintframework.com/" },
      { name: "Onlineocr", url: "https://www.onlineocr.net/" },
      { name: "Timer-tab", url: "https://www.timer-tab.com/" },
      { name: "Unblockit", url: "https://unblockit.ltd/" },
      { name: "Toffeeshare", url: "https://toffeeshare.com/" },
      { name: "GNU CAT", url: "https://gnu.cat/" },
      //Inspo
      { name: "Product Hunt", url: "https://www.producthunt.com/" },
      { name: "Behance", url: "https://www.behance.net/" },
      { name: "Dribbbe", url: "https://dribbble.com/" },
      { name: "Brand New", url: "https://www.underconsideration.com/brandnew/" },
      { name: "SP/webdevhome", url: "https://webdevhome.github.io/" },
      { name: "SP/weboas.is", url: "https://weboas.is/" },
      { name: "Goodsites.tech", url: "https://www.goodsites.tech/" },
      { name: "Learnxinyminutes", url: "https://learnxinyminutes.com/" },
      { name: "Deviantart", url: "https://www.deviantart.com" },
      { name: "Artstation", url: "https://www.artstation.com" },
    ],
  },
  {
    title: "XD",
    links: [
//reddit alternatives
      { name: "Ruqqus (R)", url: "https://ruqqus.com/" },
      { name: "Communities (R)", url: "https://communities.win/" },
      { name: "Saidit (R)", url: "https://saidit.net/" },
      { name: "Lemmy (R)", url: "https://lemmy.ml/" },
      { name: "Poal.co (R)", url: "https://poal.co/" },
      { name: "Tildes (R)", url: "https://tildes.net" },
      { name: "Libredd.it (R)", url: "https://libredd.it" }, //(front-end mirror for reddit)
      { name: "Teddit (R)", url: "https://teddit.net/" }, //(front-end mirror for reddit)
//youtube alternatives
      { name: "D.tube (YT)", url: "https://d.tube/" },
      { name: "Odysee (YT)", url: "https://odysee.com/" },
      { name: "Storyfire (YT)", url: "https://storyfire.com/" },
      { name: "Bitchute (YT)", url: "https://www.bitchute.com/" },
      { name: "Invidio (YT)", url: "https://invidio.us/" }, //(front-end mirror for youtube)
//twitch.TV alternatives
      { name: "Bitwave (TV)", url: "https://www.bitchute.com/" },
      { name: "Dlive (TV)", url: "https://dlive.tv/" },
      { name: "Trovo (TV)", url: "https://trovo.live/" },
//twitter alternatives
      { name: "Mastodon (T)", url: "https://joinmastodon.org/" },
      { name: "Minds (T)", url: "https://www.minds.com/" },
      { name: "Nitter (T)", url: "https://nitter.net" }, //(front-end mirror for twitter)
//instagram alternatives
      { name: "Pixelfed (I)", url: "https://pixelfed.org/" },
      { name: "Tiblar (I)", url: "https://tiblar.com" },
      { name: "Bibliogram (I)", url: "https://bibliogram.art" }, //(front-end mirror for Instagram)
//facebook alternatives
      { name: "Gab (F)", url: "https://gab.com" },
      { name: "Brax (F)", url: "https://brax.me/" },
      { name: "Diasporafoundation (F)", url: "https://diasporafoundation.org/" },
      { name: "Friendi (F)", url: "https://friendi.ca/" },
      //(most of the) sites extracted from this crap https://ghostbin.co/paste/hwzn6
    ],
  },
];
